//allprojects {
//    repositories {
//        google()
//        mavenCentral()
//    }
//}
//
//rootProject.buildDir = "../build"
//subprojects {
//    project.buildDir = "${rootProject.buildDir}/${project.name}"
//}
//subprojects {
//    project.evaluationDependsOn(":app")
//}
//
//tasks.register("clean", Delete) {
//    delete rootProject.buildDir
//}
//
//buildscript {
//    ext.kotlin_version = '1.9.0' // 📍 코틀린 버전 상향
//    repositories {
//        google()
//        mavenCentral()
//    }
//
//    dependencies {
//        // 📍 Gradle 플러그인 버전을 8.0 이상으로 권장합니다.
//        classpath 'com.android.tools.build:gradle:8.1.0'
//        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
//    }
//}

buildscript {
    ext.kotlin_version = '1.9.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // AGP(Android Gradle Plugin)와 Kotlin 플러그인 설정
        classpath 'com.android.tools.build:gradle:8.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
